//@version=6
indicator("Keltner Channels", overlay=true)

length = input.int(20, minval=1, title="Length")
mult = input.float(2.0, title="Multiplier")
src = input(close, title="Source")
useTrueRange = input(true, title="Use True Range")

ma = ta.ema(src, length)
rangema = ta.ema(useTrueRange ? ta.tr : high - low, length)

upper = ma + rangema * mult
lower = ma - rangema * mult

u = plot(upper, color=#2962FF, title="Upper")
plot(ma, color=#2962FF, title="Basis")
l = plot(lower, color=#2962FF, title="Lower")

fill(u, l, color=color.rgb(33, 150, 243, 95), title="Background")
