
// ========================================
// TIER 4: EXPANSION (1200+) - Waves, UAD, PA, Kontakt Libs
// ========================================
// --- Waves (Complete Mercury/Abbey Road/SSL/etc) ---
{ n: 'Waves Tune Real-Time', m: 'Waves', c: 'エフェクト', a: 'Waves', u: 'https://www.waves.com/plugins/waves-tune-real-time', dl: 'https://www.waves.com/downloads' },
{ n: 'Waves Tune', m: 'Waves', c: 'エフェクト', a: 'Waves', u: 'https://www.waves.com/plugins/waves-tune', dl: '' },
{ n: 'OVox Vocal ReSynthesis', m: 'Waves', c: 'エフェクト', a: 'Waves', u: 'https://www.waves.com/plugins/ovox-vocal-resynthesis', dl: '' },
{ n: 'Clarity Vx', m: 'Waves', c: 'エフェクト', a: 'Waves', u: 'https://www.waves.com/plugins/clarity-vx', dl: '' },
{ n: 'Clarity Vx Pro', m: 'Waves', c: 'エフェクト', a: 'Waves', u: 'https://www.waves.com/plugins/clarity-vx-pro', dl: '' },
{ n: 'Clarity Vx DeReverb', m: 'Waves', c: 'エフェクト', a: 'Waves', u: 'https://www.waves.com/plugins/clarity-vx-dereverb', dl: '' },
{ n: 'Clarity Vx DeReverb Pro', m: 'Waves', c: 'エフェクト', a: 'Waves', u: 'https://www.waves.com/plugins/clarity-vx-dereverb-pro', dl: '' },
{ n: 'S1 Stereo Imager', m: 'Waves', c: 'エフェクト', a: 'Waves', u: 'https://www.waves.com/plugins/s1-stereo-imager', dl: '' },
{ n: 'C1 Compressor', m: 'Waves', c: 'エフェクト', a: 'Waves', u: 'https://www.waves.com/plugins/c1-compressor', dl: '' },
{ n: 'C4 Multiband Compressor', m: 'Waves', c: 'エフェクト', a: 'Waves', u: 'https://www.waves.com/plugins/c4-multiband-compressor', dl: '' },
{ n: 'C6 Multiband Compressor', m: 'Waves', c: 'エフェクト', a: 'Waves', u: 'https://www.waves.com/plugins/c6-multiband-compressor', dl: '' },
{ n: 'H-Delay Hybrid Delay', m: 'Waves', c: 'エフェクト', a: 'Waves', u: 'https://www.waves.com/plugins/h-delay-hybrid-delay', dl: '' },
{ n: 'H-Reverb Hybrid Reverb', m: 'Waves', c: 'エフェクト', a: 'Waves', u: 'https://www.waves.com/plugins/h-reverb-hybrid-reverb', dl: '' },
{ n: 'H-EQ Hybrid Equalizer', m: 'Waves', c: 'エフェクト', a: 'Waves', u: 'https://www.waves.com/plugins/h-eq-hybrid-equalizer', dl: '' },
{ n: 'H-Comp Hybrid Compressor', m: 'Waves', c: 'エフェクト', a: 'Waves', u: 'https://www.waves.com/plugins/h-comp-hybrid-compressor', dl: '' },
{ n: 'Renaissance Vox', m: 'Waves', c: 'エフェクト', a: 'Waves', u: 'https://www.waves.com/plugins/renaissance-vox', dl: '' },
{ n: 'Renaissance Bass', m: 'Waves', c: 'エフェクト', a: 'Waves', u: 'https://www.waves.com/plugins/renaissance-bass', dl: '' },
{ n: 'Renaissance Equalizer', m: 'Waves', c: 'エフェクト', a: 'Waves', u: 'https://www.waves.com/plugins/renaissance-equalizer', dl: '' },
{ n: 'Renaissance Compressor', m: 'Waves', c: 'エフェクト', a: 'Waves', u: 'https://www.waves.com/plugins/renaissance-compressor', dl: '' },
{ n: 'Renaissance Reverb', m: 'Waves', c: 'エフェクト', a: 'Waves', u: 'https://www.waves.com/plugins/renaissance-reverb', dl: '' },
{ n: 'Renaissance DeEsser', m: 'Waves', c: 'エフェクト', a: 'Waves', u: 'https://www.waves.com/plugins/renaissance-de-esser', dl: '' },
{ n: 'Renaissance Channel', m: 'Waves', c: 'エフェクト', a: 'Waves', u: 'https://www.waves.com/plugins/renaissance-channel', dl: '' },
{ n: 'Renaissance Axx', m: 'Waves', c: 'エフェクト', a: 'Waves', u: 'https://www.waves.com/plugins/renaissance-axx', dl: '' },
{ n: 'Doubler', m: 'Waves', c: 'エフェクト', a: 'Waves', u: 'https://www.waves.com/plugins/doubler', dl: '' },
{ n: 'SuperTap', m: 'Waves', c: 'エフェクト', a: 'Waves', u: 'https://www.waves.com/plugins/supertap', dl: '' },
{ n: 'Trans-X', m: 'Waves', c: 'エフェクト', a: 'Waves', u: 'https://www.waves.com/plugins/trans-x', dl: '' },
{ n: 'Vitamin Sonic Enhancer', m: 'Waves', c: 'エフェクト', a: 'Waves', u: 'https://www.waves.com/plugins/vitamin', dl: '' },
{ n: 'Center', m: 'Waves', c: 'エフェクト', a: 'Waves', u: 'https://www.waves.com/plugins/center', dl: '' },
{ n: 'SoundShifter', m: 'Waves', c: 'エフェクト', a: 'Waves', u: 'https://www.waves.com/plugins/soundshifter', dl: '' },
{ n: 'Morphoder', m: 'Waves', c: 'エフェクト', a: 'Waves', u: 'https://www.waves.com/plugins/morphoder', dl: '' },
{ n: 'GTR3', m: 'Waves', c: 'エフェクト', a: 'Waves', u: 'https://www.waves.com/plugins/gtr3', dl: '' },
{ n: 'Electric 88 Piano', m: 'Waves', c: 'インストゥルメント', a: 'Waves', u: 'https://www.waves.com/plugins/electric-88-piano', dl: '' },
{ n: 'Electric 200 Piano', m: 'Waves', c: 'インストゥルメント', a: 'Waves', u: 'https://www.waves.com/plugins/electric-200-piano', dl: '' },
{ n: 'Electric Grand 80 Piano', m: 'Waves', c: 'インストゥルメント', a: 'Waves', u: 'https://www.waves.com/plugins/electric-grand-80-piano', dl: '' },
{ n: 'Grand Rhapsody Piano', m: 'Waves', c: 'インストゥルメント', a: 'Waves', u: 'https://www.waves.com/plugins/grand-rhapsody-piano', dl: '' },
{ n: 'Clavinet', m: 'Waves', c: 'インストゥルメント', a: 'Waves', u: 'https://www.waves.com/plugins/clavinet', dl: '' },
{ n: 'Flow Motion FM Synth', m: 'Waves', c: 'インストゥルメント', a: 'Waves', u: 'https://www.waves.com/plugins/flow-motion-fm-synth', dl: '' },
{ n: 'Element 2.0', m: 'Waves', c: 'インストゥルメント', a: 'Waves', u: 'https://www.waves.com/plugins/element', dl: '' },
{ n: 'Codex Wavetable Synth', m: 'Waves', c: 'インストゥルメント', a: 'Waves', u: 'https://www.waves.com/plugins/codex', dl: '' },
{ n: 'Bass Fingers', m: 'Waves', c: 'インストゥルメント', a: 'Waves', u: 'https://www.waves.com/plugins/bass-fingers', dl: '' },
{ n: 'Bass Slapper', m: 'Waves', c: 'インストゥルメント', a: 'Waves', u: 'https://www.waves.com/plugins/bass-slapper', dl: '' },
{ n: 'CR8 Creative Sampler', m: 'Waves', c: 'インストゥルメント', a: 'Waves', u: 'https://www.waves.com/plugins/cr8-creative-sampler', dl: '' },
{ n: 'Cosmos Sample Finder', m: 'Waves', c: 'ユーティリティ', a: 'Waves', u: 'https://www.waves.com/plugins/cosmos', dl: '' },
// --- Universal Audio (Additional) ---
{ n: 'UA Verve Analog Machines', m: 'Universal Audio', c: 'エフェクト', a: '独自認証', u: 'https://www.uaudio.com/uad-plugins/verve-analog-machines.html', dl: '' },
{ n: 'UA Verve Analog Machines Essentials', m: 'Universal Audio', c: 'エフェクト', a: '独自認証', u: 'https://www.uaudio.com/uad-plugins/verve-analog-machines-essentials.html', dl: '' },
{ n: 'UA Hitsville Reverb Chambers', m: 'Universal Audio', c: 'エフェクト', a: '独自認証', u: 'https://www.uaudio.com/uad-plugins/reverbs/hitsville-reverb-chambers.html', dl: '' },
{ n: 'UA Hitsville EQ Collection', m: 'Universal Audio', c: 'エフェクト', a: '独自認証', u: 'https://www.uaudio.com/uad-plugins/equalizers/hitsville-eq-collection.html', dl: '' },
{ n: 'UA Pure Plate Reverb', m: 'Universal Audio', c: 'エフェクト', a: '独自認証', u: 'https://www.uaudio.com/uad-plugins/reverbs/pure-plate-reverb.html', dl: '' },
{ n: 'UA Manley VOXBOX Channel Strip', m: 'Universal Audio', c: 'エフェクト', a: '独自認証', u: 'https://www.uaudio.com/uad-plugins/channel-strips/manley-voxbox.html', dl: '' },
{ n: 'UA Manley Massive Passive EQ', m: 'Universal Audio', c: 'エフェクト', a: '独自認証', u: 'https://www.uaudio.com/uad-plugins/equalizers/manley-massive-passive.html', dl: '' },
{ n: 'UA Manley Variable Mu Limiter Compressor', m: 'Universal Audio', c: 'エフェクト', a: '独自認証', u: 'https://www.uaudio.com/uad-plugins/compressors-limiters/manley-variable-mu.html', dl: '' },
{ n: 'UA Avalon VT-737 Tube Channel Strip', m: 'Universal Audio', c: 'エフェクト', a: '独自認証', u: 'https://www.uaudio.com/uad-plugins/channel-strips/avalon-vt-737sp.html', dl: '' },
{ n: 'UA API 2500 Bus Compressor', m: 'Universal Audio', c: 'エフェクト', a: '独自認証', u: 'https://www.uaudio.com/uad-plugins/compressors-limiters/api-2500-bus-compressor.html', dl: '' },
{ n: 'UA API Vision Channel Strip', m: 'Universal Audio', c: 'エフェクト', a: '独自認証', u: 'https://www.uaudio.com/uad-plugins/channel-strips/api-vision-channel-strip.html', dl: '' },
{ n: 'UA API Summing', m: 'Universal Audio', c: 'エフェクト', a: '独自認証', u: 'https://www.uaudio.com/uad-plugins/luna-custom/api-summing.html', dl: '' },
{ n: 'UA Neve Summing', m: 'Universal Audio', c: 'エフェクト', a: '独自認証', u: 'https://www.uaudio.com/uad-plugins/luna-custom/neve-summing.html', dl: '' },
{ n: 'UA PolyMAX Synth', m: 'Universal Audio', c: 'インストゥルメント', a: '独自認証', u: 'https://www.uaudio.com/uad-instruments/polymax-synth.html', dl: '' },
{ n: 'UA Opal Morphing Synth', m: 'Universal Audio', c: 'インストゥルメント', a: '独自認証', u: 'https://www.uaudio.com/uad-instruments/opal-morphing-synth.html', dl: '' },
{ n: 'UA Ravel Grand Piano', m: 'Universal Audio', c: 'インストゥルメント', a: '独自認証', u: 'https://www.uaudio.com/uad-instruments/ravel-grand-piano.html', dl: '' },
// --- Plugin Alliance (Additional) ---
{ n: 'AMEK EQ 200', m: 'Plugin Alliance', c: 'エフェクト', a: '独自認証', u: 'https://www.plugin-alliance.com/en/products/amek_eq_200.html', dl: '' },
{ n: 'AMEK Mastering Compressor', m: 'Plugin Alliance', c: 'エフェクト', a: '独自認証', u: 'https://www.plugin-alliance.com/en/products/amek_mastering_compressor.html', dl: '' },
{ n: 'Bettermaker EQ232D', m: 'Plugin Alliance', c: 'エフェクト', a: '独自認証', u: 'https://www.plugin-alliance.com/en/products/bettermaker_eq232d.html', dl: '' },
{ n: 'Bettermaker Bus Compressor', m: 'Plugin Alliance', c: 'エフェクト', a: '独自認証', u: 'https://www.plugin-alliance.com/en/products/bettermaker_bus_compressor.html', dl: '' },
{ n: 'Dangerous Music BAX EQ', m: 'Plugin Alliance', c: 'エフェクト', a: '独自認証', u: 'https://www.plugin-alliance.com/en/products/dangerous_music_bax_eq.html', dl: '' },
{ n: 'Knif Audio Soma', m: 'Plugin Alliance', c: 'エフェクト', a: '独自認証', u: 'https://www.plugin-alliance.com/en/products/knif_audio_soma.html', dl: '' },
{ n: 'Harris Doyle Natalus DSCEQ', m: 'Plugin Alliance', c: 'エフェクト', a: '独自認証', u: 'https://www.plugin-alliance.com/en/products/harris_doyle_natalus_dsceq.html', dl: '' },
{ n: 'Looptrotter SA2RATE 2', m: 'Plugin Alliance', c: 'エフェクト', a: '独自認証', u: 'https://www.plugin-alliance.com/en/products/looptrotter_sa2rate_2.html', dl: '' },
{ n: 'Kiive Audio Xtressor', m: 'Plugin Alliance', c: 'エフェクト', a: '独自認証', u: 'https://www.plugin-alliance.com/en/products/kiive_audio_xtressor.html', dl: '' },
{ n: 'Kiive Audio Tape Face', m: 'Plugin Alliance', c: 'エフェクト', a: '独自認証', u: 'https://www.plugin-alliance.com/en/products/kiive_audio_tape_face.html', dl: '' },
{ n: 'Kiive Audio ADC1 Compressor', m: 'Plugin Alliance', c: 'エフェクト', a: '独自認証', u: 'https://www.plugin-alliance.com/en/products/kiive_audio_adc1_compressor.html', dl: '' },
{ n: 'Wedge Force Keemun', m: 'Plugin Alliance', c: 'インストゥルメント', a: '独自認証', u: 'https://www.plugin-alliance.com/en/products/wedge_force_keemun.html', dl: '' },
{ n: 'Wedge Force Matcha', m: 'Plugin Alliance', c: 'インストゥルメント', a: '独自認証', u: 'https://www.plugin-alliance.com/en/products/wedge_force_matcha.html', dl: '' },
{ n: 'Wedge Force Hydro', m: 'Plugin Alliance', c: 'インストゥルメント', a: '独自認証', u: 'https://www.plugin-alliance.com/en/products/wedge_force_hydro.html', dl: '' },
// --- Orchestral / Cinematic Libraries ---
{ n: 'Spitfire Chamber Strings', m: 'Spitfire Audio', c: 'インストゥルメント', a: '独自認証', u: 'https://www.spitfireaudio.com/spitfire-chamber-strings', dl: '' },
{ n: 'Spitfire Symphonic Strings', m: 'Spitfire Audio', c: 'インストゥルメント', a: '独自認証', u: 'https://www.spitfireaudio.com/spitfire-symphonic-strings', dl: '' },
{ n: 'Spitfire Solo Strings', m: 'Spitfire Audio', c: 'インストゥルメント', a: '独自認証', u: 'https://www.spitfireaudio.com/spitfire-solo-strings', dl: '' },
{ n: 'Spitfire Studio Strings', m: 'Spitfire Audio', c: 'インストゥルメント', a: '独自認証', u: 'https://www.spitfireaudio.com/spitfire-studio-strings', dl: '' },
{ n: 'Spitfire BBC Symphony Orchestra Professional', m: 'Spitfire Audio', c: 'インストゥルメント', a: '独自認証', u: 'https://www.spitfireaudio.com/bbc-symphony-orchestra-professional', dl: '' },
{ n: 'Spitfire BBC Symphony Orchestra Core', m: 'Spitfire Audio', c: 'インストゥルメント', a: '独自認証', u: 'https://www.spitfireaudio.com/bbc-symphony-orchestra-core', dl: '' },
{ n: 'Spitfire BBC Symphony Orchestra Discover', m: 'Spitfire Audio', c: 'インストゥルメント', a: '独自認証', u: 'https://www.spitfireaudio.com/bbc-symphony-orchestra-discover', dl: '' },
{ n: 'Albion One', m: 'Spitfire Audio', c: 'インストゥルメント', a: '独自認証', u: 'https://www.spitfireaudio.com/albion-one', dl: '' },
{ n: 'Albion Neo', m: 'Spitfire Audio', c: 'インストゥルメント', a: '独自認証', u: 'https://www.spitfireaudio.com/albion-neo', dl: '' },
{ n: 'Albion Solstice', m: 'Spitfire Audio', c: 'インストゥルメント', a: '独自認証', u: 'https://www.spitfireaudio.com/albion-solstice', dl: '' },
{ n: 'Albion V Tundra', m: 'Spitfire Audio', c: 'インストゥルメント', a: '独自認証', u: 'https://www.spitfireaudio.com/albion-v-tundra', dl: '' },
{ n: 'Hans Zimmer Percussion', m: 'Spitfire Audio', c: 'インストゥルメント', a: '独自認証', u: 'https://www.spitfireaudio.com/hans-zimmer-percussion', dl: '' },
{ n: 'Hans Zimmer Strings', m: 'Spitfire Audio', c: 'インストゥルメント', a: '独自認証', u: 'https://www.spitfireaudio.com/hans-zimmer-strings', dl: '' },
{ n: 'Eric Whitacre Choir', m: 'Spitfire Audio', c: 'インストゥルメント', a: '独自認証', u: 'https://www.spitfireaudio.com/eric-whitacre-choir', dl: '' },
{ n: 'Kepler Orchestra', m: 'Spitfire Audio', c: 'インストゥルメント', a: '独自認証', u: 'https://www.spitfireaudio.com/kepler-orchestra', dl: '' },
{ n: 'London Contemporary Orchestra Strings', m: 'Spitfire Audio', c: 'インストゥルメント', a: '独自認証', u: 'https://www.spitfireaudio.com/london-contemporary-orchestra-strings', dl: '' },
{ n: 'Orchestral Tools Berlin Strings', m: 'Orchestral Tools', c: 'インストゥルメント', a: 'SINE Player', u: 'https://www.orchestraltools.com/store/collections/berlin-strings', dl: 'https://www.orchestraltools.com/sine' },
{ n: 'Orchestral Tools Berlin Woodwinds', m: 'Orchestral Tools', c: 'インストゥルメント', a: 'SINE Player', u: 'https://www.orchestraltools.com/store/collections/berlin-woodwinds', dl: '' },
{ n: 'Orchestral Tools Berlin Brass', m: 'Orchestral Tools', c: 'インストゥルメント', a: 'SINE Player', u: 'https://www.orchestraltools.com/store/collections/berlin-brass', dl: '' },
{ n: 'Orchestral Tools Berlin Percussion', m: 'Orchestral Tools', c: 'インストゥルメント', a: 'SINE Player', u: 'https://www.orchestraltools.com/store/collections/berlin-percussion', dl: '' },
{ n: 'Orchestral Tools Metropolis Ark 1', m: 'Orchestral Tools', c: 'インストゥルメント', a: 'SINE Player', u: 'https://www.orchestraltools.com/store/collections/metropolis-ark-1', dl: '' },
{ n: 'Orchestral Tools Metropolis Ark 2', m: 'Orchestral Tools', c: 'インストゥルメント', a: 'SINE Player', u: 'https://www.orchestraltools.com/store/collections/metropolis-ark-2', dl: '' },
{ n: 'Orchestral Tools Metropolis Ark 3', m: 'Orchestral Tools', c: 'インストゥルメント', a: 'SINE Player', u: 'https://www.orchestraltools.com/store/collections/metropolis-ark-3', dl: '' },
{ n: 'Orchestral Tools Metropolis Ark 4', m: 'Orchestral Tools', c: 'インストゥルメント', a: 'SINE Player', u: 'https://www.orchestraltools.com/store/collections/metropolis-ark-4', dl: '' },
{ n: 'Orchestral Tools Time Macro', m: 'Orchestral Tools', c: 'インストゥルメント', a: 'SINE Player', u: 'https://www.orchestraltools.com/store/collections/time-macro', dl: '' },
{ n: 'Orchestral Tools Time Micro', m: 'Orchestral Tools', c: 'インストゥルメント', a: 'SINE Player', u: 'https://www.orchestraltools.com/store/collections/time-micro', dl: '' },
{ n: 'Heavyocity Damage 2', m: 'Heavyocity', c: 'インストゥルメント', a: 'Native Access', u: 'https://heavyocity.com/product/damage-2/', dl: '' },
{ n: 'Heavyocity Gravity 2', m: 'Heavyocity', c: 'インストゥルメント', a: 'Native Access', u: 'https://heavyocity.com/product/gravity-2/', dl: '' },
{ n: 'Heavyocity Symphonic Destruction', m: 'Heavyocity', c: 'インストゥルメント', a: 'Native Access', u: 'https://heavyocity.com/product/symphonic-destruction/', dl: '' },
{ n: 'Heavyocity Forzo', m: 'Heavyocity', c: 'インストゥルメント', a: 'Native Access', u: 'https://heavyocity.com/product/forzo-modern-brass/', dl: '' },
{ n: 'Heavyocity Novo', m: 'Heavyocity', c: 'インストゥルメント', a: 'Native Access', u: 'https://heavyocity.com/product/novo-modern-strings/', dl: '' },
{ n: 'Heavyocity Vento', m: 'Heavyocity', c: 'インストゥルメント', a: 'Native Access', u: 'https://heavyocity.com/product/vento-modern-woodwinds/', dl: '' },
{ n: 'Heavyocity Vocalise 3', m: 'Heavyocity', c: 'インストゥルメント', a: 'Native Access', u: 'https://heavyocity.com/product/vocalise-3/', dl: '' },
{ n: 'ProjectSAM Symphobia 1', m: 'ProjectSAM', c: 'インストゥルメント', a: 'Native Access', u: 'https://projectsam.com/libraries/symphobia-1/', dl: '' },
{ n: 'ProjectSAM Symphobia 2', m: 'ProjectSAM', c: 'インストゥルメント', a: 'Native Access', u: 'https://projectsam.com/libraries/symphobia-2/', dl: '' },
{ n: 'ProjectSAM Lumina', m: 'ProjectSAM', c: 'インストゥルメント', a: 'Native Access', u: 'https://projectsam.com/libraries/lumina/', dl: '' },
{ n: 'ProjectSAM Pandora', m: 'ProjectSAM', c: 'インストゥルメント', a: 'Native Access', u: 'https://projectsam.com/libraries/pandora/', dl: '' },
{ n: 'Vienna Symphonic Library Synchron Strings Pro', m: 'VSL', c: 'インストゥルメント', a: 'iLok Cloud', u: 'https://www.vsl.co.at/en/Synchron_Series/Synchron_Strings_Pro', dl: 'https://www.vsl.co.at/' },
{ n: 'Vienna Symphonic Library Synchron Brass', m: 'VSL', c: 'インストゥルメント', a: 'iLok Cloud', u: 'https://www.vsl.co.at/en/Synchron_Series/Synchron_Brass', dl: '' },
{ n: 'Vienna Symphonic Library Synchron Woodwinds', m: 'VSL', c: 'インストゥルメント', a: 'iLok Cloud', u: 'https://www.vsl.co.at/en/Synchron_Series/Synchron_Woodwinds', dl: '' },
{ n: 'Vienna Symphonic Library Synchron Percussion', m: 'VSL', c: 'インストゥルメント', a: 'iLok Cloud', u: 'https://www.vsl.co.at/en/Synchron_Series/Synchron_Percussion', dl: '' },
{ n: 'Vienna Symphonic Library Smart Orchestra', m: 'VSL', c: 'インストゥルメント', a: 'iLok Cloud', u: 'https://www.vsl.co.at/en/Synchron_Series/Smart_Orchestra', dl: '' },
{ n: '8Dio Majestica', m: '8Dio', c: 'インストゥルメント', a: 'Native Access', u: 'https://8dio.com/products/majestica', dl: '' },
{ n: '8Dio Lacrimosa', m: '8Dio', c: 'インストゥルメント', a: 'Native Access', u: 'https://8dio.com/products/lacrimosa-epic-choir', dl: '' },
{ n: '8Dio Adagio Strings', m: '8Dio', c: 'インストゥルメント', a: 'Native Access', u: 'https://8dio.com/products/adagio-violins', dl: '' },
// --- Output (Additional) ---
{ n: 'Substance', m: 'Output', c: 'インストゥルメント', a: 'Output Hub', u: 'https://output.com/products/substance', dl: '' },
{ n: 'Analog Strings', m: 'Output', c: 'インストゥルメント', a: 'Output Hub', u: 'https://output.com/products/analog-strings', dl: '' },
{ n: 'Analog Brass & Winds', m: 'Output', c: 'インストゥルメント', a: 'Output Hub', u: 'https://output.com/products/analog-brass-winds', dl: '' },
{ n: 'Movement', m: 'Output', c: 'エフェクト', a: 'Output Hub', u: 'https://output.com/products/movement', dl: '' },
{ n: 'Portal', m: 'Output', c: 'エフェクト', a: 'Output Hub', u: 'https://output.com/products/portal', dl: '' },
{ n: 'Thermal', m: 'Output', c: 'エフェクト', a: 'Output Hub', u: 'https://output.com/products/thermal', dl: '' },
// --- Cableguys (Additional) ---
{ n: 'ShaperBox 3', m: 'Cableguys', c: 'エフェクト', a: '独自認証', u: 'https://www.cableguys.com/shaperbox.html', dl: '' },
{ n: 'HalfTime', m: 'Cableguys', c: 'エフェクト', a: '独自認証', u: 'https://www.cableguys.com/halftime.html', dl: '' },
{ n: 'Curve 2', m: 'Cableguys', c: 'インストゥルメント', a: '独自認証', u: 'https://www.cableguys.com/curve.html', dl: '' },
// --- Kilohearts (Additional) ---
{ n: 'Phase Plant', m: 'Kilohearts', c: 'インストゥルメント', a: 'Kilohearts Installer', u: 'https://kilohearts.com/products/phase_plant', dl: '' },
{ n: 'Multipass', m: 'Kilohearts', c: 'エフェクト', a: 'Kilohearts Installer', u: 'https://kilohearts.com/products/multipass', dl: '' },
{ n: 'Snap Heap', m: 'Kilohearts', c: 'エフェクト', a: 'Kilohearts Installer', u: 'https://kilohearts.com/products/snap_heap', dl: '' },
{ n: 'Disperser', m: 'Kilohearts', c: 'エフェクト', a: 'Kilohearts Installer', u: 'https://kilohearts.com/products/disperser', dl: '' },
{ n: 'Faturator', m: 'Kilohearts', c: 'エフェクト', a: 'Kilohearts Installer', u: 'https://kilohearts.com/products/faturator', dl: '' },
